version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
      - localstack
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT: http://localstack:4566
    command: >
      /bin/sh -c "export AWS_REGION=us-east-1 && 
                  export AWS_ACCESS_KEY_ID=test && 
                  export AWS_SECRET_ACCESS_KEY=test && 
                  export AWS_ENDPOINT=http://localstack:4566 &&
                  java -jar app.jar"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydb
      SPRING_DATASOURCE_PASSWORD: mysqlpass
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
      AWS_REGION: us-east-1
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb,ec2
      - DEBUG=1
