spring.application.name=java-local-development-workshop
server.port=8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=catalog-service
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.testcontainers.catalog.domain.models

#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/test?sslmode=disable
spring.datasource.url=jdbc:postgresql://0.0.0.0:5432/test?sslmode=disable
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none


spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

application.product-images-bucket-name=product-images
application.product-image-updates-topic=product-image-updates
application.inventory-service-url=http://localhost:8081

cloud.aws.region.static=us-east-1
